### ISSUE TITLE
Keyword constructor for named tuples

### ISSUE THREAD

**Issue by jlperla** [mauro3/Parameters.jl#55]
This is intended to be a discussion point for an implementation of https://discourse.julialang.org/t/macro-challenge-factory-for-creating-named-tuples/9748/20  The idea would be for a v0.7 factor for creating named tuples with defaults in a type-safe way.

**Comment by ArnavSood** [comment]
@mauro3 Let me know when you're done moving/we can take a look. I like Jesse's idea of starting simple. So I wrote some tests and docs that cover the behavior we expect from the v0.6 version (which is the behavior we actually get from BramTayl's code). They're at [my fork](github.com/ArnavSood/Parameters.jl), but I'll hold off on a pull request until we can review it. 

In order to complete the 0.6 version, here's what I think we'll need to do/may want to do:

1. The code from the Discourse accepts a series of assignments, e.g. `@with_kw(x = 1, y = 2, ...)`. In order to get the type you specified, `@with_kw (x = 1, y = 2, ...)`, I think we will need to add a layer that parses the `:tuple`-type expression into a series of sub-expressions. In other words:

```julia
julia> test = :(x = 1, y = 2)
:((x = 1, y = 2))

julia> test.args[1]
:(x = 1)

julia> test.args[2]
:(y = 2)
```

From there, we can run these sub-expressions directly into the code from the Discourse. 

2. We may want to write an error message on `@with_kw` that flags if it receives a tuple of assignments, which is something like `MethodError: You may have forgotten a space...`. 

3. Regarding the error with `f = f`, it's interesting that this is a subtype of a much more general error. For example, something similar happens whenever we modify bindings we're using elsewhere in the tuple:

```julia
julia> y = 3
3

julia> @with_kw(y = 5, c = y)()
(y = 5, c = 5)
```

Likewise, we have the following, where the same variable is used in two spots, but is delayed. This gives us the same error as `@with_kw(f=f)`.

```julia
julia> x = 2
2

julia> y = 3
3

julia> @with_kw(x = y, y = x)()
ERROR: UndefVarError: y not defined
```

In each case, variables in the Main namespace are left untouched. I'm not sure exactly why symbols from different "parts" of the assignment are overwriting each other. That's something we'll have to look into. 

@jlperla, let me know what you think too.

**Comment by ArnavSood** [comment]
(Re the error, I think the spirit of the original fix (interpolating the results in between the parsing and the passing to `@NT` is generally the right kind of thing. We'll have to be careful about doing this without `eval` (maybe, grabbing the result with `getfield(Main, arg)` instead of running code), and should probably `try...catch` an undefined value error (say, if there is no corresponding field, just return the symbol we passed in). That way we don't need an extra quote layer. But that's something we can talk about later, and probably after we look at the error some more.

**Comment by jlperla** [comment]
@bramtayl   See above for a way to create the general issue with the coode you had provided.  Any thoughts on how to get these things behaving with more typical scoping rules/hygiiene?

The basic problem is that the current setup does things like the following
```
julia> y = 3
3

julia> @with_kw(y = 5, c = y)()
(y = 5, c = 5)
```

**Comment by jlperla** [comment]
@mauro3  Any hope of getting a release tagged?  It would be great to be able to use this feature in production.

**Comment by mauro3** [comment]
Sorry, I forgot!  Done now.

**Comment by jlperla** [comment]
@mauro3  @ArnavSood  Thanks so much for everything on this!  I am excited to start using this functionality.

**Comment by mauro3** [comment]
Tag is now in METADATA.
